-- ============================================================
-- 010 — YouTube footage check: who already filmed these elevators?
-- Generated by scripts/check_youtube.py. Run in the Supabase SQL Editor.
--
-- yt-dlp YouTube search on 2026-07-23; a video counts only when its title
-- has an elevator term AND a full/>=80% name match to the building
-- (near-misses: scripts/youtube_evidence.csv, status=review).
-- yt_videos = 0 means "no footage FOUND as of yt_checked" — absence
-- can't be proven, so the UI must date the claim, never say never.
-- ============================================================

alter table buildings add column if not exists yt_videos  integer,
                      add column if not exists yt_url     text,
                      add column if not exists yt_checked date;

update buildings set yt_videos = 10, yt_url = 'https://www.youtube.com/watch?v=t1XN8G2OYjI', yt_checked = '2026-07-23' where id = 3;
update buildings set yt_videos = 6, yt_url = 'https://www.youtube.com/watch?v=v8VrEqCchxM', yt_checked = '2026-07-23' where id = 4;
update buildings set yt_videos = 12, yt_url = 'https://www.youtube.com/watch?v=3nsiTZCbXEo', yt_checked = '2026-07-23' where id = 6;
update buildings set yt_videos = 15, yt_url = 'https://www.youtube.com/watch?v=h6yZdGtDHXU', yt_checked = '2026-07-23' where id = 8;
update buildings set yt_videos = 9, yt_url = 'https://www.youtube.com/watch?v=NgxCNDcMqno', yt_checked = '2026-07-23' where id = 9;
update buildings set yt_videos = 7, yt_url = 'https://www.youtube.com/watch?v=1XRXR-TOojs', yt_checked = '2026-07-23' where id = 11;
update buildings set yt_videos = 14, yt_url = 'https://www.youtube.com/watch?v=wSn50YczQnQ', yt_checked = '2026-07-23' where id = 13;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 14;
update buildings set yt_videos = 14, yt_url = 'https://www.youtube.com/watch?v=1YrE0_FHFqU', yt_checked = '2026-07-23' where id = 15;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 16;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=EuXZlNw5RGI', yt_checked = '2026-07-23' where id = 17;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 20;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=AES7OgxNjng', yt_checked = '2026-07-23' where id = 21;
update buildings set yt_videos = 7, yt_url = 'https://www.youtube.com/watch?v=xVGPrQgutt4', yt_checked = '2026-07-23' where id = 22;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 23;
update buildings set yt_videos = 15, yt_url = 'https://www.youtube.com/watch?v=LD6wyJDDDNA', yt_checked = '2026-07-23' where id = 25;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 26;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 28;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 29;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 31;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 32;
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=wB0r8UCmG-8', yt_checked = '2026-07-23' where id = 33;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Xe3sJJJxw80', yt_checked = '2026-07-23' where id = 34;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=AzysEQyHLBg', yt_checked = '2026-07-23' where id = 35;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=Lhs8bqUa1jA', yt_checked = '2026-07-23' where id = 36;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 37;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 38;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=uAhyt_h3iUs', yt_checked = '2026-07-23' where id = 39;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=r1qlsQMhP9U', yt_checked = '2026-07-23' where id = 41;
update buildings set yt_videos = 6, yt_url = 'https://www.youtube.com/watch?v=w6CLLf6tuEY', yt_checked = '2026-07-23' where id = 42;
update buildings set yt_videos = 13, yt_url = 'https://www.youtube.com/watch?v=x4--Et2_IUk', yt_checked = '2026-07-23' where id = 43;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 44;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=3PiOgSzCd7I', yt_checked = '2026-07-23' where id = 46;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=ZdX-wRuYWM4', yt_checked = '2026-07-23' where id = 48;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Xi0OcmJPWBI', yt_checked = '2026-07-23' where id = 50;
update buildings set yt_videos = 6, yt_url = 'https://www.youtube.com/watch?v=XJaYrmjR4rU', yt_checked = '2026-07-23' where id = 51;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 52;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 53;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 55;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 58;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 59;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 62;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 63;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=St4CzVoQspQ', yt_checked = '2026-07-23' where id = 67;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=cOOQFypusCA', yt_checked = '2026-07-23' where id = 70;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=rgexp1PbOl8', yt_checked = '2026-07-23' where id = 74;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=24_Jd-fR5O8', yt_checked = '2026-07-23' where id = 75;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 76;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 77;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=za_EjG78QUY', yt_checked = '2026-07-23' where id = 78;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=SZKN7nd2sSg', yt_checked = '2026-07-23' where id = 88;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 90;
update buildings set yt_videos = 11, yt_url = 'https://www.youtube.com/watch?v=rRjAVLGgDC4', yt_checked = '2026-07-23' where id = 91;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 95;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 96;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 97;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=FXB_9Y51xvs', yt_checked = '2026-07-23' where id = 98;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=R4eydV6oE0g', yt_checked = '2026-07-23' where id = 99;
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=nwLrOIuHX9Y', yt_checked = '2026-07-23' where id = 100;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 101;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 102;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 109;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 112;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 113;
update buildings set yt_videos = 15, yt_url = 'https://www.youtube.com/watch?v=5KAh9Sh9H2o', yt_checked = '2026-07-23' where id = 124;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 125;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=yRZ1OGl0Ato', yt_checked = '2026-07-23' where id = 127;
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=ZEZO7yiWvNc', yt_checked = '2026-07-23' where id = 128;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=VBKBctA84C0', yt_checked = '2026-07-23' where id = 129;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 130;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 131;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 141;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=Yp4nRrm7m1g', yt_checked = '2026-07-23' where id = 150;
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=Vlv_y0Pybdg', yt_checked = '2026-07-23' where id = 151;
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=WqkreVmNRZs', yt_checked = '2026-07-23' where id = 152;
update buildings set yt_videos = 7, yt_url = 'https://www.youtube.com/watch?v=K-03LkvW-B0', yt_checked = '2026-07-23' where id = 158;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 159;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 167;
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=LGrVubLF8NY', yt_checked = '2026-07-23' where id = 168;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 169;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=lIW11MD8EBc', yt_checked = '2026-07-23' where id = 174;
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=VQzBIG2NmKE', yt_checked = '2026-07-23' where id = 177;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 180;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 182;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 185;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 186;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 187;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 189;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 194;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 196;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=lW9-cfooyUM', yt_checked = '2026-07-23' where id = 197;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 203;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 207;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 208;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 209;
update buildings set yt_videos = 10, yt_url = 'https://www.youtube.com/watch?v=Osk9S56GrS0', yt_checked = '2026-07-23' where id = 210;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 211;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=a8hGqiZw9ck', yt_checked = '2026-07-23' where id = 212;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 214;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 218;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=m7YksE7AAbg', yt_checked = '2026-07-23' where id = 219;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 220;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 224;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=s_Kq0piS30k', yt_checked = '2026-07-23' where id = 225;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 228;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 234;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=3bZE2WwBXzo', yt_checked = '2026-07-23' where id = 244;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 247;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 248;
update buildings set yt_videos = 13, yt_url = 'https://www.youtube.com/watch?v=Z-yxTaK9gqE', yt_checked = '2026-07-23' where id = 251;
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=mPpH9SKNXng', yt_checked = '2026-07-23' where id = 253;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=5KzVEBvIEnw', yt_checked = '2026-07-23' where id = 254;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=X0Ru9yFYpBU', yt_checked = '2026-07-23' where id = 255;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=7SeWFcNGakw', yt_checked = '2026-07-23' where id = 256;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=6wAf00RtlfQ', yt_checked = '2026-07-23' where id = 257;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 259;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=0_SYBG_7hI8', yt_checked = '2026-07-23' where id = 262;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 263;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 264;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 269;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 295;
update buildings set yt_videos = 6, yt_url = 'https://www.youtube.com/watch?v=mWHn86rk0Zc', yt_checked = '2026-07-23' where id = 302;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 305;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=QyNlT-NoPjM', yt_checked = '2026-07-23' where id = 331;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 360;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 362;
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=GrfbJJweCZk', yt_checked = '2026-07-23' where id = 372;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 375;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 377;
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=3CBxCOupvo8', yt_checked = '2026-07-23' where id = 383;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 384;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 385;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 389;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=FILKH_GAY4o', yt_checked = '2026-07-23' where id = 392;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=eOCbusfI_Fk', yt_checked = '2026-07-23' where id = 404;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 409;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=qOoj0EIEGX8', yt_checked = '2026-07-23' where id = 432;
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=FSF3zW_uUnY', yt_checked = '2026-07-23' where id = 436;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=z8kdR5grqoM', yt_checked = '2026-07-23' where id = 437;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 438;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=VJMbAhnalzQ', yt_checked = '2026-07-23' where id = 439;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 442;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 443;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 444;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 447;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=_uiZK0v-HAk', yt_checked = '2026-07-23' where id = 448;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 452;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 455;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 457;
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=LNfPIvGnayk', yt_checked = '2026-07-23' where id = 462;
update buildings set yt_videos = 13, yt_url = 'https://www.youtube.com/watch?v=LthEDxKfWcQ', yt_checked = '2026-07-23' where id = 483;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 491;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 511;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 512;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 537;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 541;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 542;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=li2ZcT6lwaI', yt_checked = '2026-07-23' where id = 559;
update buildings set yt_videos = 6, yt_url = 'https://www.youtube.com/watch?v=1DH4feQYLBY', yt_checked = '2026-07-23' where id = 561;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 574;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 575;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 576;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 581;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 583;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 584;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=ECqsWRXC_Sg', yt_checked = '2026-07-23' where id = 587;
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=z3GQcong4AU', yt_checked = '2026-07-23' where id = 590;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 591;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 592;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 594;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 597;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 599;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 601;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 602;
update buildings set yt_videos = 0, yt_url = null, yt_checked = '2026-07-23' where id = 615;

-- Sanity check:
select count(*) filter (where yt_checked is not null) as checked,
       count(*) filter (where yt_videos = 0)          as unfilmed,
       count(*) filter (where yt_videos > 0)          as filmed
from buildings;
