-- ============================================================
-- 013 — Human triage of ambiguous coverage matches
-- Selin reviewed every near-miss candidate (scripts/triage.html);
-- yes -> confirmed coverage, all-no -> an honest "none found".
-- Undecided buildings keep NULL. Generated by build_triage.py --sql.
-- ============================================================

update buildings set reddit_posts = 1, reddit_url = 'https://www.reddit.com/r/longisland/comments/1q0nhb4/roosevelt_field_mall/' where id = 3;  -- Roosevelt Field Mall
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=4XNqHGFrwOE' where id = 20;  -- Huntington Hospital (Northwell Health)
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Zzv-S6D7OgY' where id = 23;  -- Good Samaritan University Hospital
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Fr5IdA5m6bQ' where id = 29;  -- South Shore University Hospital
update buildings set yt_videos = 0, yt_url = null where id = 31;  -- Eastern Long Island Hospital
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=Nx1zihQaYDA' where id = 32;  -- Stony Brook Southampton Hospital
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Xe3sJJJxw80' where id = 34;  -- St. Francis Hospital The Heart Center
update buildings set yt_videos = 0, yt_url = null where id = 37;  -- Syosset Hospital
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=IxltxRbJR6w' where id = 42;  -- St. Charles Hospital
update buildings set yt_videos = 0, yt_url = null where id = 43;  -- St. Joseph Hospital
update buildings set yt_videos = 0, yt_url = null where id = 44;  -- South Oaks Hospital
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=Xi0OcmJPWBI' where id = 50;  -- 900 Stewart Ave
update buildings set yt_videos = 0, yt_url = null where id = 52;  -- 175 Broadhollow Rd
update buildings set yt_videos = 0, yt_url = null where id = 53;  -- 1010 Northern Blvd
update buildings set yt_videos = 0, yt_url = null where id = 62;  -- 1111 Marcus Ave
update buildings set yt_videos = 0, yt_url = null where id = 63;  -- 400 Crossways Park Drive
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=srqkX6xCmrY' where id = 77;  -- Hampton Inn Long Island Commack
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=PIxV71iHJ90' where id = 90;  -- SUNY Old Westbury — Campus Center
update buildings set yt_videos = 0, yt_url = null where id = 102;  -- Nassau County Courthouse
update buildings set yt_videos = 0, yt_url = null where id = 112;  -- Hempstead Town Hall
update buildings set reddit_posts = 1, reddit_url = 'https://www.reddit.com/r/NEWSDAYauto/comments/6k3d9x/local_elevator_repair_coming_to_tully_park_north/' where id = 112;  -- Hempstead Town Hall
update buildings set yt_videos = 0, yt_url = null where id = 113;  -- Suffolk County Family Court
update buildings set yt_videos = 0, yt_url = null where id = 125;  -- Port Washington Public Library
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=VBKBctA84C0' where id = 130;  -- MacArthur Airport Parking Garage
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Sb82nq7jQzM' where id = 167;  -- 100 Motor Pkwy
update buildings set yt_videos = 0, yt_url = null where id = 169;  -- 999 Stewart Avenue
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=RWc3Uz0Rv1Y' where id = 194;  -- Gurney's Star Island Resort
update buildings set yt_videos = 0, yt_url = null where id = 197;  -- The Maidstone Hotel
update buildings set yt_videos = 0, yt_url = null where id = 203;  -- Sunset Beach Hotel
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=cVoI4cSuw7E' where id = 207;  -- American Hotel Sag Harbor
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=5QJQDvAe2Ac' where id = 211;  -- Stony Brook University — Life Sciences Bldg
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=xN2krZ-9avw' where id = 220;  -- North Hempstead Town Hall
update buildings set reddit_posts = 1, reddit_url = 'https://www.reddit.com/r/NEWSDAYauto/comments/6k3d9x/local_elevator_repair_coming_to_tully_park_north/' where id = 220;  -- North Hempstead Town Hall
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=u8l6r5alI3I' where id = 224;  -- East Hampton Town Hall
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=T_MnajCC8R0' where id = 234;  -- Lynbrook Gardens
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=UnSCQZoF2tY' where id = 247;  -- Great Neck Public Library — Main Branch
update buildings set yt_videos = 0, yt_url = null where id = 248;  -- Babylon Public Library
update buildings set yt_videos = 0, yt_url = null where id = 259;  -- Stony Brook University Sports Complex
update buildings set yt_videos = 0, yt_url = null where id = 389;  -- Patchogue Theatre for the Performing Arts
update buildings set yt_videos = 0, yt_url = null where id = 409;  -- Nassau County Museum of Art
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=PzZR3absc0Y' where id = 442;  -- Commack Public Library
update buildings set yt_videos = 0, yt_url = null where id = 443;  -- North Babylon Public Library
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=Su1i7CZHRgw' where id = 444;  -- Elmont Public Library
update buildings set yt_videos = 0, yt_url = null where id = 455;  -- Farmingdale Village Hall
update buildings set yt_videos = 0, yt_url = null where id = 457;  -- New Hyde Park Village Hall
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=VIkiH_WWYuM' where id = 537;  -- East Hampton Village Green
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=cVoI4cSuw7E' where id = 574;  -- Sag Harbor Village Hall
update buildings set yt_videos = 0, yt_url = null where id = 584;  -- Garden City High School
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=acK3sqMwB_M' where id = 592;  -- Planting Fields — Coe Hall
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=EuXZlNw5RGI' where id = 615;  -- Jericho Terrace Plaza
update buildings set yt_videos = 0, yt_url = null where id = 1000;  -- Brunswick Hospital Center
update buildings set yt_videos = 0, yt_url = null where id = 1001;  -- South Woods Middle School
update buildings set yt_videos = 0, yt_url = null where id = 1004;  -- Saint Joseph's Roman Catholic Church
update buildings set yt_videos = 0, yt_url = null where id = 1011;  -- Buiding 2
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=_O_KBK53gWc' where id = 1012;  -- FairField Metro
update buildings set yt_videos = 0, yt_url = null where id = 1013;  -- North District Lofts
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=jf5xC06Qr1M' where id = 1015;  -- Northport Veterans Hospital
update buildings set yt_videos = 4, yt_url = 'https://www.youtube.com/watch?v=v8VrEqCchxM' where id = 1018;  -- Stony Brook Eastern Long Island Hospital
update buildings set yt_videos = 0, yt_url = null where id = 1024;  -- Mount Sinai South Nassau
update buildings set yt_videos = 0, yt_url = null where id = 1025;  -- Sun Valley
update buildings set yt_videos = 0, yt_url = null where id = 1026;  -- Ammann College
update buildings set yt_videos = 0, yt_url = null where id = 1027;  -- Gray College
update buildings set yt_videos = 0, yt_url = null where id = 1034;  -- The Tides Motor Inn
update buildings set reddit_posts = 0, reddit_url = null where id = 1037;  -- Holiday Inn
update buildings set yt_videos = 0, yt_url = null where id = 1037;  -- Holiday Inn
update buildings set yt_videos = 0, yt_url = null where id = 1038;  -- 1377 Motor Parkway
update buildings set yt_videos = 0, yt_url = null where id = 1039;  -- NYU Langone Hospital-Suffolk
update buildings set yt_videos = 0, yt_url = null where id = 1041;  -- Natural Science Bulding
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=B15iMPVbT-Q' where id = 1043;  -- Lupton Hall
update buildings set yt_videos = 0, yt_url = null where id = 1044;  -- Montauk Tower
update buildings set yt_videos = 0, yt_url = null where id = 1045;  -- Roger Memorial Library
update buildings set yt_videos = 3, yt_url = 'https://www.youtube.com/watch?v=PhDqZKBcqJw' where id = 1047;  -- Thompson Hall
update buildings set yt_videos = 5, yt_url = 'https://www.youtube.com/watch?v=Jq0N_Zb256c' where id = 1048;  -- Whitman Hall
update buildings set yt_videos = 0, yt_url = null where id = 1050;  -- Good Samaritan Hospital Medical Center
update buildings set yt_videos = 0, yt_url = null where id = 1053;  -- The Grand Rehabilitation and Nursing
update buildings set yt_videos = 0, yt_url = null where id = 1055;  -- Marshall Hall
update buildings set yt_videos = 0, yt_url = null where id = 1057;  -- Bolivar Hall
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=1mj2CbChUMw' where id = 1058;  -- Kennedy Hall
update buildings set yt_videos = 0, yt_url = null where id = 1060;  -- Maple Crest
update buildings set yt_videos = 0, yt_url = null where id = 1061;  -- Northwell Health Urgent Care
update buildings set yt_videos = 0, yt_url = null where id = 1062;  -- The President Apartments
update buildings set yt_videos = 0, yt_url = null where id = 1066;  -- Springfield Apartment
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=JMf-cKz91IU' where id = 1070;  -- Roosevelt Hall
update buildings set yt_videos = 0, yt_url = null where id = 1071;  -- King Hall
update buildings set yt_videos = 0, yt_url = null where id = 1072;  -- Anthony Hall
update buildings set yt_videos = 0, yt_url = null where id = 1074;  -- Social and Behavioral Sciences
update buildings set reddit_posts = 0, reddit_url = null where id = 1075;  -- Light Engineering
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=uz2jYxExmUk' where id = 1076;  -- Health Sciences Center
update buildings set yt_videos = 0, yt_url = null where id = 1077;  -- Basic Sciences Tower
update buildings set yt_videos = 0, yt_url = null where id = 1079;  -- Hendrix College
update buildings set yt_videos = 0, yt_url = null where id = 1080;  -- Chelsea Plaza
update buildings set yt_videos = 0, yt_url = null where id = 1081;  -- 1 Townhouse Place
update buildings set yt_videos = 0, yt_url = null where id = 1082;  -- Maestro
update buildings set yt_videos = 2, yt_url = 'https://www.youtube.com/watch?v=V-Og-cVdacs' where id = 1083;  -- Nassau University Medical Center
update buildings set yt_videos = 0, yt_url = null where id = 1085;  -- Village Square
update buildings set yt_videos = 0, yt_url = null where id = 1088;  -- Physical Fitness Center
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=L4xTaPKg6g0' where id = 1089;  -- Peconic Bay Medical Center
update buildings set yt_videos = 1, yt_url = 'https://www.youtube.com/watch?v=8Wz9kTPLnoA' where id = 1091;  -- NYU Langone Hospital Long Island
update buildings set yt_videos = 0, yt_url = null where id = 1092;  -- Horizon of Westbury

-- Sanity check:
select count(*) filter (where yt_videos is null or reddit_posts is null) as still_no_claim,
       count(*) filter (where yt_videos = 0 and reddit_posts = 0) as be_the_first
from buildings;
