#!/usr/bin/env python3
"""
Assemble the human-triage worklist: every building whose coverage is NULL
("no claim") because the only matches were near-misses. Each candidate video/
post is shown to a human who decides yes (it IS this building's elevator),
no, or skip. Decisions land in scripts/triage_decisions.json (written by
triage_server.py) and become migration 013 via --sql.

Semantics of a decision, per building and source:
  - any yes  -> confirmed coverage: count = number of yes candidates
  - all no   -> an honest 0: "none found" (the near-misses are ruled out)
  - any skip (and no yes) -> stays NULL
"""
import json, os, sys
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_youtube import check_building

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
YT = os.path.join(ROOT, "scripts", "youtube_report.json")
RD = os.path.join(ROOT, "scripts", "reddit_report.json")
IMP = os.path.join(ROOT, "scripts", "osm_import_report.json")
OUT = os.path.join(ROOT, "scripts", "triage_data.json")
DECISIONS = os.path.join(ROOT, "scripts", "triage_decisions.json")
MIGRATION = os.path.join(ROOT, "migrations", "013_triage_decisions.sql")


def emit_sql():
    """Turn human triage decisions into migration 013. Per building & source:
    any yes -> confirmed (count = yes count, url = first yes); all candidates
    no -> an honest 0; any undecided (and no yes) -> stays NULL, no update."""
    data = {b["id"]: b for b in json.load(open(OUT))}
    dec = json.load(open(DECISIONS))
    col = {"youtube": ("yt_videos", "yt_url"), "reddit": ("reddit_posts", "reddit_url")}
    lines = [
        "-- ============================================================",
        "-- 013 — Human triage of ambiguous coverage matches",
        "-- Selin reviewed every near-miss candidate (scripts/triage.html);",
        "-- yes -> confirmed coverage, all-no -> an honest \"none found\".",
        "-- Undecided buildings keep NULL. Generated by build_triage.py --sql.",
        "-- ============================================================", ""]
    n = 0
    for bid, b in sorted(data.items()):
        d = dec.get(str(bid), {})
        by_src = {}
        for c in b["candidates"]:
            by_src.setdefault(c["source"], []).append(c)
        for src, cands in by_src.items():
            votes = [d.get(f'{c["source"]}|{c["url"]}') for c in cands]
            yes = [c for c, v in zip(cands, votes) if v == "yes"]
            cnt_col, url_col = col[src]
            if yes:
                url = yes[0]["url"].replace("'", "''")
                lines.append(f"update buildings set {cnt_col} = {len(yes)}, {url_col} = '{url}' where id = {bid};  -- {b['name']}")
                n += 1
            elif all(v == "no" for v in votes):
                lines.append(f"update buildings set {cnt_col} = 0, {url_col} = null where id = {bid};  -- {b['name']}")
                n += 1
    lines += ["", "-- Sanity check:",
              "select count(*) filter (where yt_videos is null or reddit_posts is null) as still_no_claim,",
              "       count(*) filter (where yt_videos = 0 and reddit_posts = 0) as be_the_first",
              "from buildings;", ""]
    open(MIGRATION, "w").write("\n".join(lines))
    print(f"Wrote {MIGRATION} ({n} updates)")


if "--sql" in sys.argv:
    emit_sql()
    sys.exit()

items = {}


def add(bid, name, town, source, cands):
    if not cands:
        return
    it = items.setdefault(bid, {"id": bid, "name": name, "town": town, "candidates": []})
    for c in cands:
        it["candidates"].append({"source": source, "title": c["title"], "url": c["url"],
                                 "channel": c.get("channel") or c.get("subreddit")})


yt = json.load(open(YT))["buildings"]
for bid, b in yt.items():
    if not b["confirmed"] and b["review"]:
        add(int(bid), b["name"], b["town"], "youtube", b["review"][:5])

rd = json.load(open(RD))["buildings"]
for bid, b in rd.items():
    if not b.get("error") and not b["confirmed"] and b["review"]:
        add(int(bid), b["name"], b["town"], "reddit", b["review"][:5])

# Imported buildings: review titles were never stored — re-search them now.
imp = json.load(open(IMP))["buildings"]
todo = [c for c in imp if c.get("yt", {}).get("videos") == 0 and c["yt"].get("review")]
print(f"re-searching {len(todo)} imported buildings for their near-miss titles")
with ThreadPoolExecutor(max_workers=4) as pool:
    futs = {pool.submit(check_building, c): c for c in todo}
    for fut in as_completed(futs):
        r = fut.result()
        if not r.get("error"):
            add(r["id"], r["name"], r["town"], "youtube", r["review"][:5])

out = sorted(items.values(), key=lambda x: x["id"])
json.dump(out, open(OUT, "w"), indent=1)
n = sum(len(i["candidates"]) for i in out)
print(f"{len(out)} buildings, {n} candidates -> {OUT}")
