#!/usr/bin/env python3
"""
Assemble the human-triage worklist: every building whose coverage is NULL
("no claim") because the only matches were near-misses. Each candidate video/
post is shown to a human who decides yes (it IS this building's elevator),
no, or skip. Decisions land in scripts/triage_decisions.json (written by
triage_server.py) and become a migration via --sql.

Two worklists, one decisions ledger (building ids never collide):
  default   the original LI pass -> triage_data.json,     migration 013
  --qbk     Queens/Brooklyn 016  -> triage_data_qbk.json, migration 017

The import reports only store candidate COUNTS, so held buildings are
re-searched here to recover the actual titles/urls (resumes into the
worklist file). Serve with:
  python3 scripts/triage_server.py [scripts/triage_data_qbk.json]

Semantics of a decision, per building and source:
  - any yes  -> confirmed coverage: count = number of yes candidates
  - all no   -> an honest 0: "none found" (the near-misses are ruled out)
  - any skip (and no yes) -> stays NULL
"""
import argparse, json, os, sys, time
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_youtube import check_building
from check_reddit import arctic, classify_posts
from recheck_coverage import elsewhere

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
YT = os.path.join(ROOT, "scripts", "youtube_report.json")
RD = os.path.join(ROOT, "scripts", "reddit_report.json")
IMP = os.path.join(ROOT, "scripts", "osm_import_report.json")
QBK = os.path.join(ROOT, "scripts", "osm_import_report_qbk.json")
DECISIONS = os.path.join(ROOT, "scripts", "triage_decisions.json")

QBK_SUBS = [("Elevators", "{name}"), ("elevator", "{name}"),
            ("nyc", "{name} elevator"), ("brooklyn", "{name} elevator"),
            ("queens", "{name} elevator")]


def paths(qbk):
    out = os.path.join(ROOT, "scripts", f"triage_data{'_qbk' if qbk else ''}.json")
    mig = os.path.join(ROOT, "migrations",
                       "017_triage_qbk.sql" if qbk else "013_triage_decisions.sql")
    return out, mig


def emit_sql(qbk):
    """Turn human triage decisions into a migration. Per building & source:
    any yes -> confirmed (count = yes count, url = first yes); all candidates
    no -> an honest 0; any undecided (and no yes) -> stays NULL, no update."""
    out, mig = paths(qbk)
    data = {b["id"]: b for b in json.load(open(out))}
    dec = json.load(open(DECISIONS))
    col = {"youtube": ("yt_videos", "yt_url"), "reddit": ("reddit_posts", "reddit_url")}
    num = os.path.basename(mig)[:3]
    scope = "Queens/Brooklyn import (016)" if qbk else "coverage checks (010/012)"
    lines = [
        "-- ============================================================",
        f"-- {num} — Human triage of ambiguous coverage matches, {scope}",
        "-- Selin reviewed every near-miss candidate (scripts/triage.html);",
        "-- yes -> confirmed coverage, all-no -> an honest \"none found\".",
        "-- Undecided buildings keep NULL. Generated by build_triage.py --sql.",
        "-- ============================================================", ""]
    n = 0
    for bid, b in sorted(data.items()):
        d = dec.get(str(bid), {})
        by_src = {}
        for c in b["candidates"]:
            by_src.setdefault(c["source"], []).append(c)
        for src, cands in by_src.items():
            votes = [d.get(f'{c["source"]}|{c["url"]}') for c in cands]
            yes = [c for c, v in zip(cands, votes) if v == "yes"]
            cnt_col, url_col = col[src]
            if yes:
                url = yes[0]["url"].replace("'", "''")
                lines.append(f"update buildings set {cnt_col} = {len(yes)}, {url_col} = '{url}' where id = {bid};  -- {b['name']}")
                n += 1
            elif all(v == "no" for v in votes):
                lines.append(f"update buildings set {cnt_col} = 0, {url_col} = null where id = {bid};  -- {b['name']}")
                n += 1
    lines += ["", "-- Sanity check:",
              "select count(*) filter (where yt_videos is null or reddit_posts is null) as still_no_claim,",
              "       count(*) filter (where yt_videos = 0 and reddit_posts = 0) as be_the_first",
              "from buildings;", ""]
    open(mig, "w").write("\n".join(lines))
    print(f"Wrote {mig} ({n} updates)")


def add(items, bid, name, town, source, cands):
    # A near-miss whose title names another state is junk, not a maybe.
    cands = [c for c in cands if not elsewhere(c["title"])]
    if not cands:
        return
    it = items.setdefault(bid, {"id": bid, "name": name, "town": town, "candidates": []})
    for c in cands:
        it["candidates"].append({"source": source, "title": c["title"], "url": c["url"],
                                 "channel": c.get("channel") or c.get("subreddit")})


def save(items, out):
    rows = sorted(items.values(), key=lambda x: x["id"])
    json.dump(rows, open(out, "w"), indent=1)
    return rows


def build_li(out):
    items = {}
    yt = json.load(open(YT))["buildings"]
    for bid, b in yt.items():
        if not b["confirmed"] and b["review"]:
            add(items, int(bid), b["name"], b["town"], "youtube", b["review"][:5])

    rd = json.load(open(RD))["buildings"]
    for bid, b in rd.items():
        if not b.get("error") and not b["confirmed"] and b["review"]:
            add(items, int(bid), b["name"], b["town"], "reddit", b["review"][:5])

    # Imported buildings: review titles were never stored — re-search them now.
    imp = json.load(open(IMP))["buildings"]
    todo = [c for c in imp if c.get("yt", {}).get("videos") == 0 and c["yt"].get("review")]
    print(f"re-searching {len(todo)} imported buildings for their near-miss titles")
    with ThreadPoolExecutor(max_workers=4) as pool:
        futs = {pool.submit(check_building, c): c for c in todo}
        for fut in as_completed(futs):
            r = fut.result()
            if not r.get("error"):
                add(items, r["id"], r["name"], r["town"], "youtube", r["review"][:5])
    return save(items, out)


def build_qbk(out):
    """The 016 import stored only candidate counts; recover titles by
    re-running both searches for every held building. Resumes: buildings
    already in the worklist (or ruled in the ledger) are skipped."""
    imp = json.load(open(QBK))["buildings"]
    items = {b["id"]: b for b in json.load(open(out))} if os.path.exists(out) else {}
    done = set(items)

    yt_todo = [c for c in imp if c["id"] not in done
               and c.get("yt", {}).get("videos") == 0 and c["yt"].get("review")]
    print(f"YouTube re-search: {len(yt_todo)} held buildings")
    n = 0
    with ThreadPoolExecutor(max_workers=4) as pool:
        futs = {pool.submit(check_building, c): c for c in yt_todo}
        for fut in as_completed(futs):
            r = fut.result()
            n += 1
            if not r.get("error"):
                add(items, r["id"], r["name"], r["town"], "youtube", r["review"][:5])
            if n % 20 == 0:
                print(f"yt {n}/{len(yt_todo)}", flush=True)
                save(items, out)

    rd_todo = [c for c in imp if c.get("rd", {}).get("posts") == 0 and c["rd"].get("review")]
    print(f"Reddit re-search: {len(rd_todo)} held buildings (serial, archive rate limits)")
    for i, c in enumerate(rd_todo, 1):
        # A building can be held on both sources; only skip the reddit search
        # if this exact source's candidates are already in the worklist.
        if any(x["source"] == "reddit" for x in items.get(c["id"], {}).get("candidates", [])):
            continue
        posts = []
        failed = False
        for sub, q in QBK_SUBS:
            got = arctic(sub, q.format(name=c["name"]))
            if got is None:
                failed = True
                break
            posts += [{"title": p.get("title"), "subreddit": p.get("subreddit"),
                       "permalink": p.get("permalink"), "score": p.get("score"),
                       "body": (p.get("selftext") or "")[:4000]} for p in got]
            time.sleep(2.0)
        if failed:
            print(f"rd #{c['id']} throttled, cooling down 60s", flush=True)
            time.sleep(60)
            continue
        conf, rev = classify_posts({"name": c["name"], "town": c["town"]}, posts)
        add(items, c["id"], c["name"], c["town"], "reddit", (conf + rev)[:5])
        if i % 10 == 0:
            print(f"rd {i}/{len(rd_todo)}", flush=True)
            save(items, out)
    return save(items, out)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--qbk", action="store_true")
    ap.add_argument("--sql", action="store_true")
    a = ap.parse_args()
    if a.sql:
        emit_sql(a.qbk)
    else:
        out, _ = paths(a.qbk)
        rows = build_qbk(out) if a.qbk else build_li(out)
        n = sum(len(i["candidates"]) for i in rows)
        print(f"{len(rows)} buildings, {n} candidates -> {out}")
